// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/aws/amazon-vpc-cni-k8s/pkg/apis/crd/v1alpha1"
	scheme "github.com/aws/amazon-vpc-cni-k8s/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ENIConfigsGetter has a method to return a ENIConfigInterface.
// A group's client should implement this interface.
type ENIConfigsGetter interface {
	ENIConfigs() ENIConfigInterface
}

// ENIConfigInterface has methods to work with ENIConfig resources.
type ENIConfigInterface interface {
	Create(ctx context.Context, eNIConfig *v1alpha1.ENIConfig, opts v1.CreateOptions) (*v1alpha1.ENIConfig, error)
	Update(ctx context.Context, eNIConfig *v1alpha1.ENIConfig, opts v1.UpdateOptions) (*v1alpha1.ENIConfig, error)
	UpdateStatus(ctx context.Context, eNIConfig *v1alpha1.ENIConfig, opts v1.UpdateOptions) (*v1alpha1.ENIConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ENIConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ENIConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ENIConfig, err error)
	ENIConfigExpansion
}

// eNIConfigs implements ENIConfigInterface
type eNIConfigs struct {
	client rest.Interface
}

// newENIConfigs returns a ENIConfigs
func newENIConfigs(c *CrdV1alpha1Client) *eNIConfigs {
	return &eNIConfigs{
		client: c.RESTClient(),
	}
}

// Get takes name of the eNIConfig, and returns the corresponding eNIConfig object, and an error if there is any.
func (c *eNIConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ENIConfig, err error) {
	result = &v1alpha1.ENIConfig{}
	err = c.client.Get().
		Resource("eniconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ENIConfigs that match those selectors.
func (c *eNIConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ENIConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ENIConfigList{}
	err = c.client.Get().
		Resource("eniconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested eNIConfigs.
func (c *eNIConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("eniconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a eNIConfig and creates it.  Returns the server's representation of the eNIConfig, and an error, if there is any.
func (c *eNIConfigs) Create(ctx context.Context, eNIConfig *v1alpha1.ENIConfig, opts v1.CreateOptions) (result *v1alpha1.ENIConfig, err error) {
	result = &v1alpha1.ENIConfig{}
	err = c.client.Post().
		Resource("eniconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(eNIConfig).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a eNIConfig and updates it. Returns the server's representation of the eNIConfig, and an error, if there is any.
func (c *eNIConfigs) Update(ctx context.Context, eNIConfig *v1alpha1.ENIConfig, opts v1.UpdateOptions) (result *v1alpha1.ENIConfig, err error) {
	result = &v1alpha1.ENIConfig{}
	err = c.client.Put().
		Resource("eniconfigs").
		Name(eNIConfig.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(eNIConfig).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *eNIConfigs) UpdateStatus(ctx context.Context, eNIConfig *v1alpha1.ENIConfig, opts v1.UpdateOptions) (result *v1alpha1.ENIConfig, err error) {
	result = &v1alpha1.ENIConfig{}
	err = c.client.Put().
		Resource("eniconfigs").
		Name(eNIConfig.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(eNIConfig).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the eNIConfig and deletes it. Returns an error if one occurs.
func (c *eNIConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("eniconfigs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *eNIConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("eniconfigs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched eNIConfig.
func (c *eNIConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ENIConfig, err error) {
	result = &v1alpha1.ENIConfig{}
	err = c.client.Patch(pt).
		Resource("eniconfigs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
