// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/amazon-vpc-cni-k8s/pkg/sagemakerwrapper (interfaces: SageMaker)

// Package mock_sagemakerwrapper is a generated GoMock package.
package mock_sagemakerwrapper

import (
	context "context"
	reflect "reflect"

	sagemaker "github.com/aws/aws-sdk-go-v2/service/sagemaker"
	gomock "github.com/golang/mock/gomock"
)

// MockSageMaker is a mock of SageMaker interface.
type MockSageMaker struct {
	ctrl     *gomock.Controller
	recorder *MockSageMakerMockRecorder
}

// MockSageMakerMockRecorder is the mock recorder for MockSageMaker.
type MockSageMakerMockRecorder struct {
	mock *MockSageMaker
}

// NewMockSageMaker creates a new mock instance.
func NewMockSageMaker(ctrl *gomock.Controller) *MockSageMaker {
	mock := &MockSageMaker{ctrl: ctrl}
	mock.recorder = &MockSageMakerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSageMaker) EXPECT() *MockSageMakerMockRecorder {
	return m.recorder
}

// AttachClusterNodeNetworkInterface mocks base method.
func (m *MockSageMaker) AttachClusterNodeNetworkInterface(arg0 context.Context, arg1 *sagemaker.AttachClusterNodeNetworkInterfaceInput, arg2 ...func(*sagemaker.Options)) (*sagemaker.AttachClusterNodeNetworkInterfaceOutput, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AttachClusterNodeNetworkInterface", varargs...)
	ret0, _ := ret[0].(*sagemaker.AttachClusterNodeNetworkInterfaceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AttachClusterNodeNetworkInterface indicates an expected call of AttachClusterNodeNetworkInterface.
func (mr *MockSageMakerMockRecorder) AttachClusterNodeNetworkInterface(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachClusterNodeNetworkInterface", reflect.TypeOf((*MockSageMaker)(nil).AttachClusterNodeNetworkInterface), varargs...)
}
