{{$POD_THROUGHPUT := DefaultParam .CL2_CNI_POD_THROUGHPUT 20}}
{{$NAMESPACE_PREFIX := DefaultParam .CL2_CNI_NAMESPACE_PREFIX "cni-scale"}}
{{$LOAD_MODULE := DefaultParam .CL2_CNI_LOAD_MODULE_PATH "cni-load-module.yaml"}}
{{$CLEANUP_SCRIPT := DefaultParam .CL2_CNI_CLEANUP_SCRIPT "/bin/false"}}
{{$CLEANUP_TIMEOUT := DefaultParam .CL2_CNI_CLEANUP_TIMEOUT "30m"}}

name: cni-scale-manual
namespace:
  number: 1
  prefix: {{$NAMESPACE_PREFIX}}
  deleteStaleNamespaces: true
  deleteAutomanagedNamespaces: false
tuningSets:
- name: UniformQPS
  qpsLoad:
    qps: {{$POD_THROUGHPUT}}
steps:
- module:
    path: {{$LOAD_MODULE}}
- name: Clean up CNI scale workload
  measurements:
  - Identifier: CleanupCNIScaleWorkload
    Method: Exec
    Params:
      timeout: {{$CLEANUP_TIMEOUT}}
      command:
      - /bin/bash
      - {{$CLEANUP_SCRIPT}}
