apiVersion: v1
kind: Config
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://127.0.0.1:65535
  name: dry-run
contexts:
- context:
    cluster: dry-run
    user: dry-run
  name: dry-run
current-context: dry-run
users:
- name: dry-run
  user:
    token: dry-run
