apiVersion: v1
kind: Pod
metadata:
  name: {{.Name}}
  labels:
    group: cni-scale
spec:
  automountServiceAccountToken: false
  nodeSelector:
    kubernetes.io/os: linux
  terminationGracePeriodSeconds: 0
  topologySpreadConstraints:
  - labelSelector:
      matchLabels:
        group: cni-scale
    maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
  containers:
  - name: workload
    image: {{.Image}}
    imagePullPolicy: IfNotPresent
    command:
    - sleep
    - "604800"
    resources:
      requests:
        cpu: 5m
        memory: 8Mi
