# To validate:
#   cat codecov.yml | curl --data-binary @- https://codecov.io/validate

codecov:
  # Avoid "Missing base report"
  # https://docs.codecov.io/docs/comparing-commits
  allow_coverage_offsets: true
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...75"

  status:
    project:
      default:
        threshold: 1
      unittest:
        threshold: 1
        only_pulls: true
        flags:
          - "unittest"
    # Disable patch since it is noisy and not correct
    patch:
      default:
        enabled: no
        if_not_found: success

comment: false

ignore:
  - "cmd/**/main.go"
  - "config/**/*"
  - "docs/**/*"
  - "misc/**/*"
  - "rpc/**/*"
  - "scripts/**/*"
  - "test/**/*"
  - "testdata/**/*"
