# To validate:
#   cat codecov.yml | curl --data-binary @- https://codecov.io/validate

codecov:
  notify:
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        threshold: 1
      unittest:
        threshold: 1
        only_pulls: true
        flags:
          - "unittest"
    patch:
      default:
        threshold: 1
        only_pulls: true
      unittest:
        threshold: 1
        only_pulls: true
        flags:
          - "unittest"
    changes: no

comment: false

ignore:
  - "test/**/*"
  - "testdata/**/*"
