// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	rpc.proto

It has these top-level messages:
	AddNetworkRequest
	AddNetworkReply
	DelNetworkRequest
	DelNetworkReply
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddNetworkRequest struct {
	K8S_POD_NAME               string `protobuf:"bytes,1,opt,name=K8S_POD_NAME,json=K8SPODNAME" json:"K8S_POD_NAME,omitempty"`
	K8S_POD_NAMESPACE          string `protobuf:"bytes,2,opt,name=K8S_POD_NAMESPACE,json=K8SPODNAMESPACE" json:"K8S_POD_NAMESPACE,omitempty"`
	K8S_POD_INFRA_CONTAINER_ID string `protobuf:"bytes,3,opt,name=K8S_POD_INFRA_CONTAINER_ID,json=K8SPODINFRACONTAINERID" json:"K8S_POD_INFRA_CONTAINER_ID,omitempty"`
	Netns                      string `protobuf:"bytes,4,opt,name=Netns" json:"Netns,omitempty"`
	IfName                     string `protobuf:"bytes,5,opt,name=IfName" json:"IfName,omitempty"`
}

func (m *AddNetworkRequest) Reset()                    { *m = AddNetworkRequest{} }
func (m *AddNetworkRequest) String() string            { return proto.CompactTextString(m) }
func (*AddNetworkRequest) ProtoMessage()               {}
func (*AddNetworkRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddNetworkRequest) GetK8S_POD_NAME() string {
	if m != nil {
		return m.K8S_POD_NAME
	}
	return ""
}

func (m *AddNetworkRequest) GetK8S_POD_NAMESPACE() string {
	if m != nil {
		return m.K8S_POD_NAMESPACE
	}
	return ""
}

func (m *AddNetworkRequest) GetK8S_POD_INFRA_CONTAINER_ID() string {
	if m != nil {
		return m.K8S_POD_INFRA_CONTAINER_ID
	}
	return ""
}

func (m *AddNetworkRequest) GetNetns() string {
	if m != nil {
		return m.Netns
	}
	return ""
}

func (m *AddNetworkRequest) GetIfName() string {
	if m != nil {
		return m.IfName
	}
	return ""
}

type AddNetworkReply struct {
	Success      bool   `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
	IPv4Addr     string `protobuf:"bytes,2,opt,name=IPv4Addr" json:"IPv4Addr,omitempty"`
	IPv4Subnet   string `protobuf:"bytes,3,opt,name=IPv4Subnet" json:"IPv4Subnet,omitempty"`
	DeviceNumber int32  `protobuf:"varint,4,opt,name=DeviceNumber" json:"DeviceNumber,omitempty"`
}

func (m *AddNetworkReply) Reset()                    { *m = AddNetworkReply{} }
func (m *AddNetworkReply) String() string            { return proto.CompactTextString(m) }
func (*AddNetworkReply) ProtoMessage()               {}
func (*AddNetworkReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddNetworkReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AddNetworkReply) GetIPv4Addr() string {
	if m != nil {
		return m.IPv4Addr
	}
	return ""
}

func (m *AddNetworkReply) GetIPv4Subnet() string {
	if m != nil {
		return m.IPv4Subnet
	}
	return ""
}

func (m *AddNetworkReply) GetDeviceNumber() int32 {
	if m != nil {
		return m.DeviceNumber
	}
	return 0
}

type DelNetworkRequest struct {
	K8S_POD_NAME               string `protobuf:"bytes,1,opt,name=K8S_POD_NAME,json=K8SPODNAME" json:"K8S_POD_NAME,omitempty"`
	K8S_POD_NAMESPACE          string `protobuf:"bytes,2,opt,name=K8S_POD_NAMESPACE,json=K8SPODNAMESPACE" json:"K8S_POD_NAMESPACE,omitempty"`
	K8S_POD_INFRA_CONTAINER_ID string `protobuf:"bytes,3,opt,name=K8S_POD_INFRA_CONTAINER_ID,json=K8SPODINFRACONTAINERID" json:"K8S_POD_INFRA_CONTAINER_ID,omitempty"`
	IPv4Addr                   string `protobuf:"bytes,4,opt,name=IPv4Addr" json:"IPv4Addr,omitempty"`
}

func (m *DelNetworkRequest) Reset()                    { *m = DelNetworkRequest{} }
func (m *DelNetworkRequest) String() string            { return proto.CompactTextString(m) }
func (*DelNetworkRequest) ProtoMessage()               {}
func (*DelNetworkRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DelNetworkRequest) GetK8S_POD_NAME() string {
	if m != nil {
		return m.K8S_POD_NAME
	}
	return ""
}

func (m *DelNetworkRequest) GetK8S_POD_NAMESPACE() string {
	if m != nil {
		return m.K8S_POD_NAMESPACE
	}
	return ""
}

func (m *DelNetworkRequest) GetK8S_POD_INFRA_CONTAINER_ID() string {
	if m != nil {
		return m.K8S_POD_INFRA_CONTAINER_ID
	}
	return ""
}

func (m *DelNetworkRequest) GetIPv4Addr() string {
	if m != nil {
		return m.IPv4Addr
	}
	return ""
}

type DelNetworkReply struct {
	Success      bool   `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
	IPv4Addr     string `protobuf:"bytes,2,opt,name=IPv4Addr" json:"IPv4Addr,omitempty"`
	DeviceNumber int32  `protobuf:"varint,3,opt,name=DeviceNumber" json:"DeviceNumber,omitempty"`
}

func (m *DelNetworkReply) Reset()                    { *m = DelNetworkReply{} }
func (m *DelNetworkReply) String() string            { return proto.CompactTextString(m) }
func (*DelNetworkReply) ProtoMessage()               {}
func (*DelNetworkReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DelNetworkReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DelNetworkReply) GetIPv4Addr() string {
	if m != nil {
		return m.IPv4Addr
	}
	return ""
}

func (m *DelNetworkReply) GetDeviceNumber() int32 {
	if m != nil {
		return m.DeviceNumber
	}
	return 0
}

func init() {
	proto.RegisterType((*AddNetworkRequest)(nil), "rpc.AddNetworkRequest")
	proto.RegisterType((*AddNetworkReply)(nil), "rpc.AddNetworkReply")
	proto.RegisterType((*DelNetworkRequest)(nil), "rpc.DelNetworkRequest")
	proto.RegisterType((*DelNetworkReply)(nil), "rpc.DelNetworkReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CNIBackend service

type CNIBackendClient interface {
	AddNetwork(ctx context.Context, in *AddNetworkRequest, opts ...grpc.CallOption) (*AddNetworkReply, error)
	DelNetwork(ctx context.Context, in *DelNetworkRequest, opts ...grpc.CallOption) (*DelNetworkReply, error)
}

type cNIBackendClient struct {
	cc *grpc.ClientConn
}

func NewCNIBackendClient(cc *grpc.ClientConn) CNIBackendClient {
	return &cNIBackendClient{cc}
}

func (c *cNIBackendClient) AddNetwork(ctx context.Context, in *AddNetworkRequest, opts ...grpc.CallOption) (*AddNetworkReply, error) {
	out := new(AddNetworkReply)
	err := grpc.Invoke(ctx, "/rpc.CNIBackend/AddNetwork", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cNIBackendClient) DelNetwork(ctx context.Context, in *DelNetworkRequest, opts ...grpc.CallOption) (*DelNetworkReply, error) {
	out := new(DelNetworkReply)
	err := grpc.Invoke(ctx, "/rpc.CNIBackend/DelNetwork", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CNIBackend service

type CNIBackendServer interface {
	AddNetwork(context.Context, *AddNetworkRequest) (*AddNetworkReply, error)
	DelNetwork(context.Context, *DelNetworkRequest) (*DelNetworkReply, error)
}

func RegisterCNIBackendServer(s *grpc.Server, srv CNIBackendServer) {
	s.RegisterService(&_CNIBackend_serviceDesc, srv)
}

func _CNIBackend_AddNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CNIBackendServer).AddNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.CNIBackend/AddNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CNIBackendServer).AddNetwork(ctx, req.(*AddNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CNIBackend_DelNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CNIBackendServer).DelNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.CNIBackend/DelNetwork",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CNIBackendServer).DelNetwork(ctx, req.(*DelNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CNIBackend_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.CNIBackend",
	HandlerType: (*CNIBackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddNetwork",
			Handler:    _CNIBackend_AddNetwork_Handler,
		},
		{
			MethodName: "DelNetwork",
			Handler:    _CNIBackend_DelNetwork_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x53, 0xcd, 0x6a, 0xf2, 0x50,
	0x10, 0x35, 0x9f, 0x3f, 0x9f, 0x0e, 0x42, 0xf0, 0x22, 0x12, 0x2c, 0x14, 0xc9, 0xaa, 0x74, 0x11,
	0x4a, 0xdb, 0x85, 0x94, 0x6e, 0xa2, 0xb1, 0x34, 0x48, 0xaf, 0x21, 0x29, 0x74, 0x19, 0x34, 0x99,
	0xb6, 0x62, 0x34, 0x69, 0x7e, 0xb4, 0xbe, 0x41, 0xa1, 0x4f, 0xd4, 0x67, 0xe8, 0x4b, 0x95, 0x7b,
	0x8d, 0x1a, 0xcd, 0xae, 0xab, 0xee, 0x66, 0xce, 0x9c, 0x03, 0xe7, 0xcc, 0xbd, 0x03, 0xb5, 0x30,
	0x70, 0x94, 0x20, 0xf4, 0x63, 0x9f, 0x14, 0xc3, 0xc0, 0x91, 0xbf, 0x05, 0x68, 0xa8, 0xae, 0x4b,
	0x31, 0x5e, 0xf9, 0xe1, 0xcc, 0xc4, 0xb7, 0x04, 0xa3, 0x98, 0x74, 0xa0, 0x3e, 0xec, 0x5a, 0xb6,
	0x31, 0xd2, 0x6c, 0xaa, 0x3e, 0x0c, 0x24, 0xa1, 0x23, 0x9c, 0xd5, 0x4c, 0x18, 0x76, 0x2d, 0x63,
	0xa4, 0x31, 0x84, 0x9c, 0x43, 0x23, 0xcb, 0xb0, 0x0c, 0xb5, 0x3f, 0x90, 0xfe, 0x71, 0x9a, 0xb8,
	0xa7, 0x71, 0x98, 0xdc, 0x40, 0x7b, 0xcb, 0xd5, 0xe9, 0x9d, 0xa9, 0xda, 0xfd, 0x11, 0x7d, 0x54,
	0x75, 0x3a, 0x30, 0x6d, 0x5d, 0x93, 0x8a, 0x5c, 0xd4, 0xda, 0x88, 0xf8, 0x7c, 0x37, 0xd6, 0x35,
	0xd2, 0x84, 0x32, 0xc5, 0x78, 0x11, 0x49, 0x25, 0x4e, 0xdb, 0x34, 0xa4, 0x05, 0x15, 0xfd, 0x99,
	0x8e, 0xe7, 0x28, 0x95, 0x39, 0x9c, 0x76, 0xf2, 0xa7, 0x00, 0x62, 0x36, 0x4d, 0xe0, 0xad, 0x89,
	0x04, 0xff, 0xad, 0xc4, 0x71, 0x30, 0x8a, 0x78, 0x8c, 0xaa, 0xb9, 0x6d, 0x49, 0x1b, 0xaa, 0xba,
	0xb1, 0xbc, 0x56, 0x5d, 0x37, 0x4c, 0xad, 0xef, 0x7a, 0x72, 0x0a, 0xc0, 0x6a, 0x2b, 0x99, 0x2c,
	0x30, 0x4e, 0x3d, 0x66, 0x10, 0x22, 0x43, 0x5d, 0xc3, 0xe5, 0xd4, 0x41, 0x9a, 0xcc, 0x27, 0x18,
	0x72, 0x7b, 0x65, 0xf3, 0x00, 0x93, 0xbf, 0x04, 0x68, 0x68, 0xe8, 0xfd, 0xd9, 0xdd, 0x66, 0xf3,
	0x97, 0x0e, 0xf3, 0xcb, 0x33, 0x10, 0xb3, 0xd6, 0x7f, 0xbf, 0xc8, 0xe3, 0x45, 0x15, 0xf3, 0x8b,
	0xba, 0xfc, 0x10, 0x00, 0xfa, 0x54, 0xef, 0x8d, 0x9d, 0x19, 0x2e, 0x5c, 0x72, 0x0b, 0xb0, 0x7f,
	0x44, 0xd2, 0x52, 0xd8, 0x97, 0xcd, 0xfd, 0xd1, 0x76, 0x33, 0x87, 0x07, 0xde, 0x5a, 0x2e, 0x30,
	0xf5, 0xde, 0x79, 0xaa, 0xce, 0xbd, 0x42, 0xaa, 0x3e, 0x8a, 0x28, 0x17, 0x7a, 0x17, 0x70, 0x32,
	0xf5, 0x95, 0x17, 0x36, 0xc4, 0xf7, 0xf1, 0x3c, 0xf0, 0x30, 0x52, 0x5e, 0xd1, 0xf3, 0xfc, 0x95,
	0x1f, 0x7a, 0x6e, 0x4f, 0xbc, 0x67, 0xf5, 0x13, 0xab, 0x0d, 0x76, 0x44, 0x86, 0x30, 0xa9, 0xf0,
	0x6b, 0xba, 0xfa, 0x09, 0x00, 0x00, 0xff, 0xff, 0x23, 0x65, 0x88, 0xdb, 0x5a, 0x03, 0x00, 0x00,
}
