{{- if .Values.cniConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aws-vpc-cni.fullname" . }}
  labels:
{{ include "aws-vpc-cni.labels" . | indent 4 }}
binaryData:
  10-aws.conflist: {{ .Values.cniConfig.fileContents | b64enc }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: amazon-vpc-cni
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "aws-vpc-cni.labels" . | indent 4 }}
data:
  enable-windows-ipam: {{ .Values.enableWindowsIpam | quote }}
  enable-network-policy-controller: {{ .Values.enableNetworkPolicy | quote }}
  enable-windows-prefix-delegation: {{ .Values.enableWindowsPrefixDelegation | quote }}

  # Linux node IP management settings
  warm-prefix-target: {{ .Values.warmPrefixTarget | quote }}
  warm-ip-target: {{ .Values.warmIPTarget | quote }}
  minimum-ip-target: {{ .Values.minimumIPTarget | quote }}

  # Windows node IP management settings
  windows-warm-prefix-target: {{ .Values.warmWindowsPrefixTarget | quote }}
  windows-warm-ip-target: {{ .Values.warmWindowsIPTarget | quote }}
  windows-minimum-ip-target: {{ .Values.minimumWindowsIPTarget | quote }}

  branch-eni-cooldown: {{ .Values.branchENICooldown | quote }}
