{{- if .Values.cniConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aws-vpc-cni.fullname" . }}
  labels:
{{ include "aws-vpc-cni.labels" . | indent 4 }}
data:
  10-aws.conflist: {{ .Values.cniConfig.fileContents | b64enc }}
{{- end -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: amazon-vpc-cni
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "aws-vpc-cni.labels" . | indent 4 }}
data:
  enable-windows-ipam: {{ .Values.enableWindowsIpam | quote }}
  enable-network-policy-controller: {{ .Values.enableNetworkPolicy | quote }}
