// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/amazon-vpc-cni-k8s/pkg/nft (interfaces: Client)

// Package mock_nft is a generated GoMock package.
package mock_nft

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	nftables "github.com/google/nftables"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// AddChain mocks base method.
func (m *MockClient) AddChain(arg0 *nftables.Chain) *nftables.Chain {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddChain", arg0)
	ret0, _ := ret[0].(*nftables.Chain)
	return ret0
}

// AddChain indicates an expected call of AddChain.
func (mr *MockClientMockRecorder) AddChain(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddChain", reflect.TypeOf((*MockClient)(nil).AddChain), arg0)
}

// AddRule mocks base method.
func (m *MockClient) AddRule(arg0 *nftables.Rule) *nftables.Rule {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRule", arg0)
	ret0, _ := ret[0].(*nftables.Rule)
	return ret0
}

// AddRule indicates an expected call of AddRule.
func (mr *MockClientMockRecorder) AddRule(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRule", reflect.TypeOf((*MockClient)(nil).AddRule), arg0)
}

// AddTable mocks base method.
func (m *MockClient) AddTable(arg0 *nftables.Table) *nftables.Table {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTable", arg0)
	ret0, _ := ret[0].(*nftables.Table)
	return ret0
}

// AddTable indicates an expected call of AddTable.
func (mr *MockClientMockRecorder) AddTable(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTable", reflect.TypeOf((*MockClient)(nil).AddTable), arg0)
}

// DelChain mocks base method.
func (m *MockClient) DelChain(arg0 *nftables.Chain) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DelChain", arg0)
}

// DelChain indicates an expected call of DelChain.
func (mr *MockClientMockRecorder) DelChain(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelChain", reflect.TypeOf((*MockClient)(nil).DelChain), arg0)
}

// DelRule mocks base method.
func (m *MockClient) DelRule(arg0 *nftables.Rule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelRule", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DelRule indicates an expected call of DelRule.
func (mr *MockClientMockRecorder) DelRule(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelRule", reflect.TypeOf((*MockClient)(nil).DelRule), arg0)
}

// DelTable mocks base method.
func (m *MockClient) DelTable(arg0 *nftables.Table) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DelTable", arg0)
}

// DelTable indicates an expected call of DelTable.
func (mr *MockClientMockRecorder) DelTable(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelTable", reflect.TypeOf((*MockClient)(nil).DelTable), arg0)
}

// Flush mocks base method.
func (m *MockClient) Flush() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush")
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockClientMockRecorder) Flush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockClient)(nil).Flush))
}

// FlushChain mocks base method.
func (m *MockClient) FlushChain(arg0 *nftables.Chain) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "FlushChain", arg0)
}

// FlushChain indicates an expected call of FlushChain.
func (mr *MockClientMockRecorder) FlushChain(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlushChain", reflect.TypeOf((*MockClient)(nil).FlushChain), arg0)
}

// GetRules mocks base method.
func (m *MockClient) GetRules(arg0 *nftables.Table, arg1 *nftables.Chain) ([]*nftables.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRules", arg0, arg1)
	ret0, _ := ret[0].([]*nftables.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRules indicates an expected call of GetRules.
func (mr *MockClientMockRecorder) GetRules(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRules", reflect.TypeOf((*MockClient)(nil).GetRules), arg0, arg1)
}

// InsertRule mocks base method.
func (m *MockClient) InsertRule(arg0 *nftables.Rule) *nftables.Rule {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRule", arg0)
	ret0, _ := ret[0].(*nftables.Rule)
	return ret0
}

// InsertRule indicates an expected call of InsertRule.
func (mr *MockClientMockRecorder) InsertRule(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRule", reflect.TypeOf((*MockClient)(nil).InsertRule), arg0)
}

// ListChain mocks base method.
func (m *MockClient) ListChain(arg0 *nftables.Table, arg1 string) (*nftables.Chain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChain", arg0, arg1)
	ret0, _ := ret[0].(*nftables.Chain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChain indicates an expected call of ListChain.
func (mr *MockClientMockRecorder) ListChain(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChain", reflect.TypeOf((*MockClient)(nil).ListChain), arg0, arg1)
}
