{
 "title": "VPC CNI IPAMD Warm Pool Testing",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(awscni_assigned_ip_addresses{job=\"aws-cni-metrics\"}, instance)"
    }
   },
   {
    "name": "ip_deletion_reason",
    "query": {
     "query": "label_values(awscni_del_ip_req_count{job=\"aws-cni-metrics\"}, reason)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Warm Pool per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "awscni_total_ip_addresses-awscni_assigned_ip_addresses",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "# of Busybox Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(awscni_assigned_ip_addresses -2)"
    }
   ]
  },
  {
   "title": "AWS Nodes",
   "type": "stat",
   "description": "\n\nnormal pods + preemptible pods should match\nthe assigned ip addresses count,\nmodulo pods using the host network",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(awscni_eni_max{k8s_app=\"aws-node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Net IP Requests[30m]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(awscni_total_ip_addresses[30m])-(max_over_time(awscni_assigned_ip_addresses[30m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Net IP Requests[24h]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "delta(awscni_assigned_ip_addresses[24h])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Warm Pool per Node",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awscni_total_ip_addresses-awscni_assigned_ip_addresses",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Max Net IP Requests[30m]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(awscni_total_ip_addresses[30m])-max_over_time(awscni_assigned_ip_addresses[30m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Net IP Requests[24h]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(awscni_assigned_ip_addresses[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "StdDev Net IP Requests[24h]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stddev_over_time(awscni_assigned_ip_addresses[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average IP Allocation per Node",
   "type": "piechart",
   "description": "Warm: total - assigned, already allocated and available\n\nCold: max - total, could be allocated",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(awscni_total_ip_addresses-awscni_assigned_ip_addresses)",
     "legendFormat": "Warm Pool (total-assigned)"
    },
    {
     "expr": "avg(awscni_ip_max-awscni_total_ip_addresses)",
     "legendFormat": "Total IPs Remaining per Node"
    },
    {
     "expr": "avg(awscni_assigned_ip_addresses)",
     "legendFormat": "Assigned IPs"
    }
   ]
  },
  {
   "title": "Cluster IP Allocation",
   "type": "piechart",
   "description": "Warm: total - assigned, already allocated and available\n\nCold: max - total, could be allocated",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(awscni_total_ip_addresses-awscni_assigned_ip_addresses)",
     "legendFormat": "Warm Pool (total-assigned)"
    },
    {
     "expr": "sum(awscni_ip_max-awscni_total_ip_addresses)",
     "legendFormat": "Total IPs Remaining"
    },
    {
     "expr": "sum(awscni_assigned_ip_addresses)",
     "legendFormat": "Assigned IPs"
    }
   ]
  },
  {
   "title": "No Available Addresses Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "delta(awscni_err_no_avail_addrs{k8s_app=\"aws-node\"}[5m])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "IP Addresses in the Cluster",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(awscni_assigned_ip_addresses)",
     "legendFormat": "Assigned IPs"
    },
    { "expr": "sum(awscni_ip_max)", "legendFormat": "IP Max per Cluster" },
    {
     "expr": "sum(awscni_total_ip_addresses-awscni_assigned_ip_addresses)",
     "legendFormat": "Warm Pool (total-assigned)"
    },
    { "expr": "sum(awscni_total_ip_addresses)", "legendFormat": "Total IPs" }
   ]
  },
  {
   "title": "All Assigned IP Addresses",
   "type": "table",
   "description": "prometheus-kube-state-metrics, grafana, prometheus-server, prometheus-pushgateway, and coredns are all not host-network",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "awscni_assigned_ip_addresses\n" }
   ]
  },
  {
   "title": "ENIs Allocated per Node",
   "type": "stat",
   "description": "\n\nCold: max - total, could be allocated",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "awscni_eni_allocated", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "IP Allocation Request per Node [5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "rate(awscni_add_ip_req_count{k8s_app=\"aws-node\"}[5m])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "IP Deallocation Request per Node [5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 29 },
   "targets": [
    {
     "expr": "delta(awscni_del_ip_req_count{k8s_app=\"aws-node\"}[5m])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "IPAMD Actions in Progress",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (fn) (awscni_ipamd_action_inprogress)",
     "legendFormat": "{{fn}}"
    }
   ]
  },
  {
   "title": "Empty ENIs per Cluster",
   "type": "stat",
   "description": "Warm: total - assigned, already allocated and available\n\nCold: max - total, could be allocated",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(1 > awscni_eni_util{k8s_app=\"aws-node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ENI Max per Node",
   "type": "stat",
   "description": "Warm: total - assigned, already allocated and available\n\nCold: max - total, could be allocated",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "awscni_eni_max", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Max IPs per ENI",
   "type": "stat",
   "description": "Warm: total - assigned, already allocated and available\n\nCold: max - total, could be allocated",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(awscni_ip_max / awscni_eni_max)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# of IPs per ENI (Labeled by Node IP) - Correlate with Allocated ENIs for Delay",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "awscni_eni_util", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average AWS API Latency [5m]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (api)(rate(awscni_aws_api_latency_ms_sum[5m])/rate(awscni_aws_api_latency_ms_count[5m]))",
     "legendFormat": "{{api}}"
    }
   ]
  }
 ]
}