ARG docker_arch
ARG golang_image=golang:1.13-stretch
FROM $golang_image
WORKDIR /go/src/github.com/aws/amazon-vpc-cni-k8s

ARG GOARCH
ARG arch
ENV ARCH=$arch

# Force the go compiler to use modules.
ENV GO111MODULE=on
ENV GOPROXY=direct

# Add goimports
RUN go get -u golang.org/x/tools/cmd/goimports

# go.mod and go.sum go into their own layers.
COPY go.mod .
COPY go.sum .

# This ensures `go mod download` happens only when go.mod and go.sum change.
RUN go mod download

COPY . .
