FROM amazonlinux:2
RUN yum update -y && \
    yum install -y iproute && \
    yum install -y iptables

WORKDIR /app

COPY aws-cni /app 

ADD aws-k8s-agent  /app
ADD scripts/aws-cni-support.sh /app
ADD scripts/install-aws.sh /app
ENTRYPOINT /app/install-aws.sh
