// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	crdv1alpha1 "github.com/aws/amazon-vpc-cni-k8s/pkg/apis/crd/v1alpha1"
	versioned "github.com/aws/amazon-vpc-cni-k8s/pkg/client/clientset/versioned"
	internalinterfaces "github.com/aws/amazon-vpc-cni-k8s/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/aws/amazon-vpc-cni-k8s/pkg/client/listers/crd/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ENIConfigInformer provides access to a shared informer and lister for
// ENIConfigs.
type ENIConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ENIConfigLister
}

type eNIConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewENIConfigInformer constructs a new informer for ENIConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewENIConfigInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredENIConfigInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredENIConfigInformer constructs a new informer for ENIConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredENIConfigInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdV1alpha1().ENIConfigs().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdV1alpha1().ENIConfigs().Watch(context.TODO(), options)
			},
		},
		&crdv1alpha1.ENIConfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *eNIConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredENIConfigInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *eNIConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&crdv1alpha1.ENIConfig{}, f.defaultInformer)
}

func (f *eNIConfigInformer) Lister() v1alpha1.ENIConfigLister {
	return v1alpha1.NewENIConfigLister(f.Informer().GetIndexer())
}
