// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/aws/amazon-vpc-cni-k8s/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// ENIConfigs returns a ENIConfigInformer.
	ENIConfigs() ENIConfigInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// ENIConfigs returns a ENIConfigInformer.
func (v *version) ENIConfigs() ENIConfigInformer {
	return &eNIConfigInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
