# https://circleci.com/docs/2.0/language-go/
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.13-stretch
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run: go get -u golang.org/x/lint/golint
      - run: go get -u golang.org/x/tools/cmd/goimports
      - run: make check-format
      - run: make build-linux
      - run: make lint
      - run: make vet
      - run: make unit-test
      
workflows:
  version: 2
  check:
    jobs:
      - build
