# https://circleci.com/docs/2.0/language-go/
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.19
  k8s: circleci/kubernetes@0.11.0
  jq: circleci/jq@2.2.0

references:
  build_job: &build
    docker:
      - image: circleci/golang:1.14-stretch
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    environment: &env
      GO111MODULE: "on"
    steps:
      - checkout
      - run: go get -u golang.org/x/lint/golint
      - run: go get -u golang.org/x/tools/cmd/goimports
      - run: make check-format
      - run: make build-linux "ARCH=$ARCH"
      # TODO: Make lint a hard-check once baselined
      - run: make lint LINT_FLAGS=
      - run: make vet
      # TODO: Enable architecture specific unit-test when Circle CI supports it!
      - run: make unit-test ARCH=amd64
      - run:
          name: Upload Coverage Results
          command: |
            curl -s https://codecov.io/bash | bash -s -- \
              -f "coverage.txt" \
              -t "${CODECOV_TOKEN}" \
              -n "${CIRCLE_BUILD_NUM}" \
              -F "" \
              -Z || echo 'Codecov upload failed'
          when: always

jobs:
  build_x86_64:
    <<: *build
    environment:
      <<: *env
      # Target the GOARCH for x86_64
      ARCH: amd64
      BUILD_MODE: "-buildmode=pie"

  build_aarch64:
    <<: *build
    environment:
      <<: *env
      # Target the GOARCH for aarch64
      ARCH: arm64
      BUILD_MODE: ""

  integration_test:
    docker:
      - image: circleci/golang:1.14-stretch
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    environment:
      <<: *env
      RUN_CONFORMANCE: "true"
    steps:
      - checkout
      - setup_remote_docker
      - aws-cli/setup:
          profile-name: awstester
      - restore_cache:
          keys:
            - dependency-packages-store-{{ checksum "test/integration/go.mod" }}
            - dependency-packages-store-
      - k8s/install-kubectl:
          # Requires at least 1.14.9 for k8s testing, since it uses log api.
          kubectl-version: v1.17.9
      - run:
          name: Run the integration tests
          command: ./scripts/run-integration-tests.sh
          no_output_timeout: 20m
      - save_cache:
          key: dependency-packages-store-{{ checksum "test/integration/go.mod" }}
          paths:
            - /go/pkg
          when: always
      - store_artifacts:
          path: /tmp/cni-test

  performance_test:
    docker:
      - image: circleci/golang:1.14-stretch
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    environment:
      <<: *env
      RUN_CONFORMANCE: "false"
      RUN_PERFORMANCE_TESTS: "true"
    steps:
      - checkout
      - jq/install
      - setup_remote_docker
      - aws-cli/setup:
          profile-name: awstester
      - restore_cache:
          keys:
            - dependency-packages-store-{{ checksum "test/integration/go.mod" }}
            - dependency-packages-store-
      - k8s/install-kubectl:
          # requires 1.14.9 for k8s testing, since it uses log api.
          kubectl-version: v1.14.9
      - run:
          name: Run the integration tests
          command: ./scripts/run-integration-tests.sh
          no_output_timeout: 15m
      - save_cache:
          key: dependency-packages-store-{{ checksum "test/integration/go.mod" }}
          paths:
            - /go/pkg
          when: always
      - store_artifacts:
          path: /tmp/cni-test

  kops_test:
    docker:
      - image: circleci/golang:1.14-stretch
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    environment:
      <<: *env
      RUN_CONFORMANCE: "false"
      RUN_KOPS_TEST: "true"
    steps:
      - checkout
      - setup_remote_docker
      - aws-cli/setup:
          profile-name: awstester
      - restore_cache:
          keys:
            - dependency-packages-store-{{ checksum "test/integration/go.mod" }}
            - dependency-packages-store-
      - k8s/install-kubectl:
          # requires 1.14.9 for k8s testing, since it uses log api.
          kubectl-version: v1.14.9
      - run:
          name: Run the integration tests
          command: ./scripts/run-integration-tests.sh
          no_output_timeout: 15m
      - save_cache:
          key: dependency-packages-store-{{ checksum "test/integration/go.mod" }}
          paths:
            - /go/pkg
          when: always
      - store_artifacts:
          path: /tmp/cni-test

  warm_ip_test:
    docker:
      - image: circleci/golang:1.14-stretch
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    environment:
      <<: *env
      RUN_WARM_IP_TEST: "true"
    steps:
      - checkout
      - setup_remote_docker
      - aws-cli/setup:
          profile-name: awstester
      - restore_cache:
          keys:
            - dependency-packages-store-{{ checksum "test/integration/go.mod" }}
            - dependency-packages-store-
      - k8s/install-kubectl:
          # requires 1.14.9 for k8s testing, since it uses log api.
          kubectl-version: v1.14.9
      - run:
          name: Run the integration tests
          command: ./scripts/run-integration-tests.sh
          no_output_timeout: 15m
      - save_cache:
          key: dependency-packages-store-{{ checksum "test/integration/go.mod" }}
          paths:
            - /go/pkg
          when: always
      - store_artifacts:
          path: /tmp/cni-test

  warm_eni_test:
    docker:
      - image: circleci/golang:1.14-stretch
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    environment:
      <<: *env
      RUN_WARM_ENI_TEST: "true"
    steps:
      - checkout
      - setup_remote_docker
      - aws-cli/setup:
          profile-name: awstester
      - restore_cache:
          keys:
            - dependency-packages-store-{{ checksum "test/integration/go.mod" }}
            - dependency-packages-store-
      - k8s/install-kubectl:
          # requires 1.14.9 for k8s testing, since it uses log api.
          kubectl-version: v1.14.9
      - run:
          name: Run the integration tests
          command: ./scripts/run-integration-tests.sh
          no_output_timeout: 15m
      - save_cache:
          key: dependency-packages-store-{{ checksum "test/integration/go.mod" }}
          paths:
            - /go/pkg
          when: always
      - store_artifacts:
          path: /tmp/cni-test

  bottlerocket_test:
    docker:
      - image: circleci/golang:1.14-stretch
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    environment:
      <<: *env
      RUN_BOTTLEROCKET_TEST: "true"
    steps:
      - checkout
      - setup_remote_docker
      - aws-cli/setup:
          profile-name: awstester
      - restore_cache:
          keys:
            - dependency-packages-store-{{ checksum "test/integration/go.mod" }}
            - dependency-packages-store-
      - k8s/install-kubectl:
          # requires 1.14.9 for k8s testing, since it uses log api.
          kubectl-version: v1.14.9
      - run:
          name: Run the integration tests
          command: ./scripts/run-integration-tests.sh
          no_output_timeout: 20m
      - save_cache:
          key: dependency-packages-store-{{ checksum "test/integration/go.mod" }}
          paths:
            - /go/pkg
          when: always
      - store_artifacts:
          path: /tmp/cni-test

workflows:
  version: 2
  check:
    jobs:
      - build_x86_64
      - build_aarch64
      - hold:
          type: approval
          requires:
            - build_x86_64
            - build_aarch64
      - integration_test:
          requires:
            - hold

  # runs integration test when new git tag is pushed.
  run-test-on-tags:
    jobs:
      - integration_test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

  # triggers daily test run on master
  nightly-test-run:
    when: ${RUN_NIGHTLY_TESTS}
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - integration_test

  # triggers weekly tests on master (Friday at 11 PM PST)
  weekly-test-run:
    when: ${RUN_WEEKLY_TESTS}
    triggers:
      - schedule:
          cron: "0 6 * * 6"
          filters:
            branches:
              only:
                - master
    jobs:
      - performance_test
      - kops_test:
          requires:
            - performance_test
      - warm_ip_test:
          requires:
            - kops_test
      - warm_eni_test:
          requires:
            - warm_ip_test
      - bottlerocket_test:
          requires:
            - warm_eni_test
