# https://circleci.com/docs/2.0/language-go/
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.19
  k8s: circleci/kubernetes@0.11.0

jobs:
  build:
    docker:
      - image: circleci/golang:1.13-stretch
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run: go get -u golang.org/x/lint/golint
      - run: go get -u golang.org/x/tools/cmd/goimports
      - run: make check-format
      - run: make build-linux
      - run: make lint
      - run: make vet
      - run: make unit-test
  integration_test:
    docker:
      - image: circleci/golang:1.13-stretch
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    environment:
      GO111MODULE: "on"
      RUN_CONFORMANCE: "true"
    steps:
      - checkout
      - setup_remote_docker
      - aws-cli/setup:
          profile-name: awstester
      - k8s/install-kubectl:
          # requires 1.14.9 for k8s testing, since it uses log api.
          kubectl-version: v1.14.9
      - run:
          name: Run the integration tests
          command: ./scripts/run-integration-tests.sh
          no_output_timeout: 15m
      - store_artifacts:
          path: /tmp/cni-test

workflows:
  version: 2
  check:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - integration_test:
          requires:
            - hold

  # runs integration test when new git tag is pushed.
  run-test-on-tags:
    jobs:
      - integration_test:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

  # triggers daily test run on master
  nightly-test-run:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - integration_test
