apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cni-metrics-helper.fullname" . }}
  labels:
{{ include "cni-metrics-helper.labels" . | indent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/proxy
    verbs: ["get", "watch", "list"]
