kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "cni-metrics-helper.fullname" . }}
  labels:
    k8s-app: cni-metrics-helper
spec:
  selector:
    matchLabels:
      k8s-app: cni-metrics-helper
  template:
    metadata:
      labels:
        k8s-app: cni-metrics-helper
    spec:
      containers:
      - env:
{{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
{{- end }}
        name: cni-metrics-helper
        image: "{{- if .Values.image.override }}{{- .Values.image.override }}{{- else }}602401143452.dkr.ecr.{{- .Values.image.region }}.amazonaws.com/cni-metrics-helper:{{- .Values.image.tag }}{{- end}}"
      serviceAccountName: {{ template "cni-metrics-helper.serviceAccountName" . }} 