// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.
//

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/amazon-vpc-cni-k8s/pkg/networkutils (interfaces: Connmark)

// Package mock_networkutils is a generated GoMock package.
package mock_networkutils

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockConnmark is a mock of Connmark interface.
type MockConnmark struct {
	ctrl     *gomock.Controller
	recorder *MockConnmarkMockRecorder
}

// MockConnmarkMockRecorder is the mock recorder for MockConnmark.
type MockConnmarkMockRecorder struct {
	mock *MockConnmark
}

// NewMockConnmark creates a new mock instance.
func NewMockConnmark(ctrl *gomock.Controller) *MockConnmark {
	mock := &MockConnmark{ctrl: ctrl}
	mock.recorder = &MockConnmarkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnmark) EXPECT() *MockConnmarkMockRecorder {
	return m.recorder
}

// Cleanup mocks base method.
func (m *MockConnmark) Cleanup() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cleanup")
	ret0, _ := ret[0].(error)
	return ret0
}

// Cleanup indicates an expected call of Cleanup.
func (mr *MockConnmarkMockRecorder) Cleanup() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cleanup", reflect.TypeOf((*MockConnmark)(nil).Cleanup))
}

// Setup mocks base method.
func (m *MockConnmark) Setup(arg0 []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Setup", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Setup indicates an expected call of Setup.
func (mr *MockConnmarkMockRecorder) Setup(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Setup", reflect.TypeOf((*MockConnmark)(nil).Setup), arg0)
}
