// Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	crdk8samazonawscomv1alpha1 "github.com/aws/amazon-vpc-cni-k8s/pkg/apis/crd.k8s.amazonaws.com/v1alpha1"
	versioned "github.com/aws/amazon-vpc-cni-k8s/pkg/client/clientset/versioned"
	internalinterfaces "github.com/aws/amazon-vpc-cni-k8s/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/aws/amazon-vpc-cni-k8s/pkg/client/listers/crd.k8s.amazonaws.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ENIConfigInformer provides access to a shared informer and lister for
// ENIConfigs.
type ENIConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ENIConfigLister
}

type eNIConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewENIConfigInformer constructs a new informer for ENIConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewENIConfigInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredENIConfigInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredENIConfigInformer constructs a new informer for ENIConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredENIConfigInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdV1alpha1().ENIConfigs().List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdV1alpha1().ENIConfigs().Watch(options)
			},
		},
		&crdk8samazonawscomv1alpha1.ENIConfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *eNIConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredENIConfigInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *eNIConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&crdk8samazonawscomv1alpha1.ENIConfig{}, f.defaultInformer)
}

func (f *eNIConfigInformer) Lister() v1alpha1.ENIConfigLister {
	return v1alpha1.NewENIConfigLister(f.Informer().GetIndexer())
}
