---
"apiVersion": "v1"
"data":
  "ADDITIONAL_ENI_TAGS": "{}"
  "AWS_VPC_CNI_NODE_PORT_SUPPORT": "true"
  "AWS_VPC_ENI_MTU": "9001"
  "AWS_VPC_K8S_CNI_CONFIGURE_RPFILTER": "false"
  "AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG": "false"
  "AWS_VPC_K8S_CNI_EXTERNALSNAT": "false"
  "AWS_VPC_K8S_CNI_LOGLEVEL": "DEBUG"
  "AWS_VPC_K8S_CNI_LOG_FILE": "/host/var/log/aws-routed-eni/ipamd.log"
  "AWS_VPC_K8S_CNI_RANDOMIZESNAT": "prng"
  "AWS_VPC_K8S_CNI_VETHPREFIX": "eni"
  "AWS_VPC_K8S_PLUGIN_LOG_FILE": "/var/log/aws-routed-eni/plugin.log"
  "AWS_VPC_K8S_PLUGIN_LOG_LEVEL": "DEBUG"
  "DISABLE_INTROSPECTION": "false"
  "DISABLE_METRICS": "false"
  "DISABLE_TCP_EARLY_DEMUX": "false"
  "ENABLE_POD_ENI": "false"
  "WARM_ENI_TARGET": "1"
"kind": "ConfigMap"
"metadata":
  "labels":
    "k8s-app": "aws-node-cm"
  "name": "aws-k8s-cni-configmap"
  "namespace": "kube-system"
...
