fullnameOverride: calico

serviceAccount:
  create: true

podSecurityPolicy:
  create: false

calico:
  tag: v3.15.1

  typha:
    logseverity: Info #Debug, Info, Warning, Error, Fatal
    image: quay.io/calico/typha
    port:
      containerPort: "5473"
    livenessProbe:
      httpGet:
        path: /liveness
        port: 9098
        host: localhost
      periodSeconds: 30
      initialDelaySeconds: 30
    readinessProbe:
      httpGet:
        path: /readiness
        port: 9098
        host: localhost
      periodSeconds: 10  
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "96Mi"
        cpu: "100m"
    tolerations: []
    nodeSelector:
      kubernetes.io/os: linux
    podAnnotations: {}
  node:
    logseverity: Info #Debug, Info, Warning, Error, Fatal
    image: quay.io/calico/node
    resources:
      requests:
        memory: "32Mi"
        cpu: "20m"
      limits:
        memory: "64Mi"
        cpu: "100m"
    extraEnv: []
    # - name: SOME_VAR
    #   value: 'some value'
    nodeSelector:
      kubernetes.io/os: linux
    podAnnotations: {}
  typha_autoscaler:
    resources:
      requests:
        memory: "16Mi"
        cpu: "10m"
      limits:
        memory: "32Mi"
        cpu: "10m"
    tolerations: []
    nodeSelector:
      kubernetes.io/os: linux
    podAnnotations: {}

autoscaler:
  tag: "1.7.1"
  image: k8s.gcr.io/cluster-proportional-autoscaler-amd64
