// Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/amazon-vpc-cni-k8s/pkg/controller/node (interfaces: MyENIProvider)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMyENIProvider is a mock of MyENIProvider interface
type MockMyENIProvider struct {
	ctrl     *gomock.Controller
	recorder *MockMyENIProviderMockRecorder
}

// MockMyENIProviderMockRecorder is the mock recorder for MockMyENIProvider
type MockMyENIProviderMockRecorder struct {
	mock *MockMyENIProvider
}

// NewMockMyENIProvider creates a new mock instance
func NewMockMyENIProvider(ctrl *gomock.Controller) *MockMyENIProvider {
	mock := &MockMyENIProvider{ctrl: ctrl}
	mock.recorder = &MockMyENIProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMyENIProvider) EXPECT() *MockMyENIProviderMockRecorder {
	return m.recorder
}

// GetMyENI mocks base method
func (m *MockMyENIProvider) GetMyENI() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyENI")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetMyENI indicates an expected call of GetMyENI
func (mr *MockMyENIProviderMockRecorder) GetMyENI() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyENI", reflect.TypeOf((*MockMyENIProvider)(nil).GetMyENI))
}
