// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/aws/amazon-vpc-cni-k8s/pkg/apis/crd/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ENIConfigLister helps list ENIConfigs.
type ENIConfigLister interface {
	// List lists all ENIConfigs in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.ENIConfig, err error)
	// Get retrieves the ENIConfig from the index for a given name.
	Get(name string) (*v1alpha1.ENIConfig, error)
	ENIConfigListerExpansion
}

// eNIConfigLister implements the ENIConfigLister interface.
type eNIConfigLister struct {
	indexer cache.Indexer
}

// NewENIConfigLister returns a new ENIConfigLister.
func NewENIConfigLister(indexer cache.Indexer) ENIConfigLister {
	return &eNIConfigLister{indexer: indexer}
}

// List lists all ENIConfigs in the indexer.
func (s *eNIConfigLister) List(selector labels.Selector) (ret []*v1alpha1.ENIConfig, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ENIConfig))
	})
	return ret, err
}

// Get retrieves the ENIConfig from the index for a given name.
func (s *eNIConfigLister) Get(name string) (*v1alpha1.ENIConfig, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("eniconfig"), name)
	}
	return obj.(*v1alpha1.ENIConfig), nil
}
