name: Nightly e2e tests

on:
  schedule:
    - cron: "0 3 * * *"  # every night

permissions:
  contents: read

jobs:
  # Run nightly e2e tests on self-hosted runner
  integration-cron:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Clean up docker
        run:  docker system prune -a --volumes -f

      - name: Clean up stale docker images
        run: docker image prune -f

      - name: Get dependencies
        run: |
          go install golang.org/x/lint/golint@latest
          go install golang.org/x/tools/cmd/goimports@latest

      - name: Run e2e tests
        env:
          DISABLE_PROMPT: true
          ROLE_CREATE: false
          ROLE_ARN: ${{ secrets.ROLE_ARN }}
          MNG_ROLE_ARN: ${{ secrets.MNG_ROLE_ARN }}
          RUN_CONFORMANCE: true
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          RUN_TESTER_LB_ADDONS: false 
          S3_BUCKET_CREATE: false
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          ./scripts/run-integration-tests.sh
