name: Integration tests

on:
  push:
    branches:
      - "master"
      - "release*"
      - "sdk*"

permissions:
  id-token: write
  contents: read

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit in the PR
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # refs/tags/v7.0.1
      - name: Set up Docker QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # refs/tags/v4.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # refs/tags/v4.2.0
      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # refs/tags/v7.0.0
        with:
          go-version: "1.26"
      - name: Set up tools
        run: |
          # Install ginkgo version from go.mod
          go install -mod=mod github.com/onsi/ginkgo/v2/ginkgo
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin/
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # refs/tags/v6.2.3
        with:
          role-to-assume: ${{ secrets.OSS_TEST_ROLE_ARN }}
          role-duration-seconds: 14400 # 4 hours
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Run e2e tests
        env:
          DISABLE_PROMPT: true
          ROLE_CREATE: false
          ROLE_ARN: ${{ secrets.EKS_CLUSTER_ROLE_ARN }}
          RUN_CONFORMANCE: true
        run: |
          ./scripts/run-integration-tests.sh
