name: Pull Request Unit Tests

on:
  pull_request:
    branches:
      - "master"
      - "release*"

permissions:
  contents: read

jobs:
  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit in the PR
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: Set up tools
        run: |
          go install golang.org/x/lint/golint@latest
          go install golang.org/x/tools/cmd/goimports@latest
      - name: Run code checks
        run: |
          make check-format
          make vet
      - name: Build
        run: make build-linux
      - name: Helm lint
        run: make helm-lint
      - name: Unit test
        run: make unit-test
      - name: Upload code coverage
        uses: codecov/codecov-action@v3
      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v3
        with:
          name: pr
          path: pr/
