name: Weekly CNI tests

on:
  schedule:
    - cron: "0 16 * * 3"  # every Wednesday

permissions:
  contents: read

jobs:
  # Run weekly tests on self-hosted runner
  weekly-cron:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Clean up docker
        run:  docker system prune -a --volumes -f

      - name: Clean up stale docker images
        run:  docker image prune -f

      - name: Get dependencies
        run: |
          go install golang.org/x/lint/golint@latest
          go install golang.org/x/tools/cmd/goimports@latest

      - name: Run perf tests
        env:
          DISABLE_PROMPT: true
          ROLE_CREATE: false
          ROLE_ARN: ${{ secrets.ROLE_ARN }}
          MNG_ROLE_ARN: ${{ secrets.MNG_ROLE_ARN }}
          RUN_PERFORMANCE_TESTS: true
          PERFORMANCE_TEST_S3_BUCKET_NAME: cni-performance-tests
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          RUN_TESTER_LB_ADDONS: true
          S3_BUCKET_CREATE: false
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          ./scripts/run-integration-tests.sh

      - name: Run kops tests
        env:
          DISABLE_PROMPT: true
          ROLE_CREATE: false
          ROLE_ARN: ${{ secrets.ROLE_ARN }}
          MNG_ROLE_ARN: ${{ secrets.MNG_ROLE_ARN }}
          RUN_KOPS_TEST: true
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          RUN_TESTER_LB_ADDONS: true
          S3_BUCKET_CREATE: false
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          ./scripts/run-integration-tests.sh
        if: always()
    
      - name: Run bottlerocket tests
        env:
          DISABLE_PROMPT: true
          ROLE_CREATE: false
          ROLE_ARN: ${{ secrets.ROLE_ARN }}
          MNG_ROLE_ARN: ${{ secrets.MNG_ROLE_ARN }}
          RUN_BOTTLEROCKET_TEST: true
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          RUN_TESTER_LB_ADDONS: true
          S3_BUCKET_CREATE: false
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          ./scripts/run-integration-tests.sh
        if: always()
    
      - name: Run calico tests
        env:
          DISABLE_PROMPT: true
          ROLE_CREATE: false
          ROLE_ARN: ${{ secrets.ROLE_ARN }}
          MNG_ROLE_ARN: ${{ secrets.MNG_ROLE_ARN }}
          RUN_CALICO_TEST: true
          RUN_LATEST_CALICO_VERSION: true
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          RUN_TESTER_LB_ADDONS: true
          S3_BUCKET_CREATE: false
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          ./scripts/run-integration-tests.sh
        if: always()
