---
"apiVersion": "rbac.authorization.k8s.io/v1"
"kind": "ClusterRoleBinding"
"metadata":
  "name": "cni-metrics-helper"
"roleRef":
  "apiGroup": "rbac.authorization.k8s.io"
  "kind": "ClusterRole"
  "name": "cni-metrics-helper"
"subjects":
- "kind": "ServiceAccount"
  "name": "cni-metrics-helper"
  "namespace": "kube-system"
---
"apiVersion": "rbac.authorization.k8s.io/v1"
"kind": "ClusterRole"
"metadata":
  "name": "cni-metrics-helper"
"rules":
- "apiGroups":
  - ""
  "resources":
  - "nodes"
  - "pods"
  - "pods/proxy"
  - "services"
  - "resourcequotas"
  - "replicationcontrollers"
  - "limitranges"
  - "persistentvolumeclaims"
  - "persistentvolumes"
  - "namespaces"
  - "endpoints"
  "verbs":
  - "list"
  - "watch"
  - "get"
- "apiGroups":
  - "extensions"
  "resources":
  - "daemonsets"
  - "deployments"
  - "replicasets"
  "verbs":
  - "list"
  - "watch"
- "apiGroups":
  - "apps"
  "resources":
  - "statefulsets"
  "verbs":
  - "list"
  - "watch"
- "apiGroups":
  - "batch"
  "resources":
  - "cronjobs"
  - "jobs"
  "verbs":
  - "list"
  - "watch"
- "apiGroups":
  - "autoscaling"
  "resources":
  - "horizontalpodautoscalers"
  "verbs":
  - "list"
  - "watch"
---
"apiVersion": "apps/v1"
"kind": "Deployment"
"metadata":
  "labels":
    "k8s-app": "cni-metrics-helper"
  "name": "cni-metrics-helper"
  "namespace": "kube-system"
"spec":
  "selector":
    "matchLabels":
      "k8s-app": "cni-metrics-helper"
  "template":
    "metadata":
      "labels":
        "k8s-app": "cni-metrics-helper"
    "spec":
      "containers":
      - "env":
        - "name": "USE_CLOUDWATCH"
          "value": "true"
        "image": "961992271922.dkr.ecr.cn-northwest-1.amazonaws.com.cn/cni-metrics-helper:v1.7.10"
        "name": "cni-metrics-helper"
      "serviceAccountName": "cni-metrics-helper"
---
"apiVersion": "v1"
"kind": "ServiceAccount"
"metadata":
  "name": "cni-metrics-helper"
  "namespace": "kube-system"
...
